package frmclient

const ReasonValidation = "VALIDATION"
const ReasonAuthorizationRequired = "AUTHORIZATION_REQUIRED"
const ReasonInactiveUser = "INACTIVE_USER"
const ReasonTechnical = "ERRCODE_TECHNICAL"
const ReasonInternal = "INTERNAL"
const ReasonServerRespondedWithError = "ERRCODE_SERVER_RESPONDED_WITH_ERROR"
const ReasonServerRespondedWithErrorNotFound = "ERRCODE_SERVER_RESPONDED_WITH_ERROR_NOT_FOUND"
const ReasonServerUnavailable = "ERRCODE_SERVER_UNAVAILABLE"
const ReasonCallerUpdateRequired = "ERRCODE_CALLER_UPDATE_REQUIRED"
const ReasonAccessDenied = "ERRCODE_ACCESS_DENIED"
const ReasonTooManyRequests = "REASON_TO_MANY_REQUESTS"

const InternalErrorMessage = "Произошла внутренняя ошибка. Мы уже занимаемся решением этой проблемы."
